import { convertToExcalidrawElements } from '@excalidraw/excalidraw'

type SceneElement = NonNullable<
  Parameters<typeof convertToExcalidrawElements>[0]
>[number]

const COLORS = {
  ink: '#263238',
  muted: '#59656a',
  blue: '#1971c2',
  blueFill: '#dbeafe',
  green: '#2b8a3e',
  greenFill: '#dcfce7',
  amber: '#e67700',
  amberFill: '#fff3bf',
  coral: '#c92a2a',
  coralFill: '#ffe3e3',
  violet: '#7048e8',
  violetFill: '#ede9fe',
  paper: '#fffdf7',
}

function text(
  x: number,
  y: number,
  value: string,
  fontSize = 24,
  color = COLORS.ink,
): SceneElement {
  return {
    type: 'text',
    x,
    y,
    text: value,
    fontSize,
    fontFamily: 2,
    strokeColor: color,
  }
}

function card(
  id: string,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  body: string,
  strokeColor: string,
  backgroundColor: string,
): SceneElement[] {
  return [
    {
      id,
      type: 'rectangle',
      x,
      y,
      width,
      height,
      strokeColor,
      backgroundColor,
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
      label: {
        text: `${title}\n\n${body}`,
        fontSize: 18,
        fontFamily: 2,
        strokeColor: COLORS.ink,
        textAlign: 'left',
        verticalAlign: 'top',
      },
    },
  ]
}

function arrow(
  x: number,
  y: number,
  width: number,
  height: number,
  color = COLORS.muted,
): SceneElement {
  return {
    type: 'arrow',
    x,
    y,
    width,
    height,
    points: [
      [0, 0],
      [width, height],
    ],
    strokeColor: color,
    strokeWidth: 2,
    endArrowhead: 'arrow',
  }
}

const skeleton: SceneElement[] = [
  text(80, 45, 'REGRESION LINEAL: MAPA DE ESTUDIO', 36, COLORS.blue),
  text(
    80,
    95,
    'Pipelines, regularizacion, evaluacion y aprendizaje online',
    21,
    COLORS.muted,
  ),
  ...card(
    'goal',
    80,
    155,
    520,
    205,
    '1. IDEA CENTRAL',
    'Aprendizaje supervisado para predecir una variable numerica.\n\ny_hat = b0 + b1*x1 + ... + bp*xp\n\nSe ajustan los coeficientes minimizando el error cuadratico. Sirve como modelo, linea base e instrumento de interpretacion.',
    COLORS.blue,
    COLORS.blueFill,
  ),
  ...card(
    'loss',
    650,
    155,
    520,
    205,
    '2. FUNCION DE PERDIDA',
    'Residuo: e_i = y_i - y_hat_i\n\nMSE = (1/n) * sum(e_i^2)\nRMSE = sqrt(MSE)\n\nRMSE queda en las mismas unidades del objetivo. Los errores grandes pesan mucho porque se elevan al cuadrado.',
    COLORS.blue,
    COLORS.blueFill,
  ),
  arrow(605, 255, 38, 0, COLORS.blue),

  text(80, 420, 'PARTE 1 · BATCH LEARNING — CALIFORNIA HOUSING', 27, COLORS.green),
  ...card(
    'dataset',
    80,
    475,
    350,
    250,
    '3. DATOS Y OBJETIVO',
    '20 640 bloques censales, 8 variables.\nObjetivo: MedHouseVal en unidades de $100k.\n\nMedInc es el predictor lineal mas fuerte (corr. aprox. 0.69). Correlacion no implica causalidad ni captura por si sola relaciones no lineales.',
    COLORS.green,
    COLORS.greenFill,
  ),
  ...card(
    'censoring',
    480,
    475,
    350,
    250,
    '4. CENSURA EN $500k',
    'Los valores superiores a $500k fueron registrados como 5.0. No son errores: solo sabemos que y >= $500k.\n\nFiltrar esas filas limita el alcance del modelo. Es una decision sobre la poblacion objetivo, no simple "limpieza".',
    COLORS.amber,
    COLORS.amberFill,
  ),
  ...card(
    'skew',
    880,
    475,
    430,
    250,
    '5. SKEWNESS (ASIMETRIA)',
    'skew = 0: distribucion simetrica\nskew > 0: cola a la derecha\nskew < 0: cola a la izquierda\n\nIMPORTANTE: no esta limitado a [-1, 1]. Como regla practica, |skew| < 1 suele considerarse aceptable; |skew| > 1 sugiere asimetria fuerte y revisar log1p.',
    COLORS.coral,
    COLORS.coralFill,
  ),
  arrow(435, 600, 38, 0, COLORS.green),
  arrow(835, 600, 38, 0, COLORS.green),

  ...card(
    'log',
    80,
    780,
    350,
    255,
    '6. TRANSFORMACION log1p',
    'log1p(x) = log(1 + x)\n\nComprime colas derechas y admite x = 0. En el lab: MedInc, AveRooms, AveBedrms, Population y AveOccup.\n\nNo se aplica por rutina: comparar antes/despues y conservar significado.',
    COLORS.amber,
    COLORS.amberFill,
  ),
  ...card(
    'leakage',
    480,
    780,
    350,
    255,
    '7. EVITAR DATA LEAKAGE',
    'Incorrecto: ajustar scaler con todos los datos y luego dividir.\n\nCorrecto: split primero; Pipeline ajusta transformaciones solo con cada fold de entrenamiento y transforma validacion con esas estadisticas.',
    COLORS.coral,
    COLORS.coralFill,
  ),
  ...card(
    'pipeline',
    880,
    780,
    430,
    255,
    '8. PIPELINE DEL LAB',
    'Datos crudos\n  -> ColumnTransformer (log/passthrough)\n  -> PolynomialFeatures\n  -> StandardScaler\n  -> Ridge\n\nLas interacciones capturan efectos como ingreso x ubicacion. Escalar es esencial antes de penalizar coeficientes.',
    COLORS.green,
    COLORS.greenFill,
  ),
  arrow(435, 910, 38, 0, COLORS.green),
  arrow(835, 910, 38, 0, COLORS.green),

  ...card(
    'regularization',
    80,
    1090,
    390,
    280,
    '9. RIDGE VS. LASSO',
    'Ridge (L2): MSE + alpha*sum(w_j^2)\nReduce todos los coeficientes; estabiliza variables correlacionadas.\n\nLasso (L1): MSE + alpha*sum(|w_j|)\nPuede llevar coeficientes exactamente a cero: seleccion de variables.\n\nalpha alto -> mas sesgo; alpha bajo -> mas varianza.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'grid',
    520,
    1090,
    350,
    280,
    '10. GRIDSEARCH + CV',
    'Probar alpha en escala logaritmica. En cada candidato, k-fold CV estima generalizacion.\n\nCurva tipica en U:\nalpha pequeno -> sobreajuste\nalpha optimo -> minimo CV RMSE\nalpha grande -> subajuste\n\nEl test se usa una sola vez al final.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'evaluation',
    920,
    1090,
    390,
    280,
    '11. EVALUAR BIEN',
    'Residual vs. prediccion: buscar nube aleatoria alrededor de 0.\nHistograma residual: revisar sesgo y colas.\n\nRMSE resume error absoluto; MAPE/|% error| muestra impacto relativo, pero explota cerca de y=0. Separar por rango revela regresion a la media.',
    COLORS.blue,
    COLORS.blueFill,
  ),
  arrow(475, 1230, 38, 0, COLORS.violet),
  arrow(875, 1230, 38, 0, COLORS.violet),

  text(80, 1440, 'PARTE 2 · ONLINE LEARNING — YEAR PREDICTION MSD', 27, COLORS.amber),
  ...card(
    'onlineWhy',
    80,
    1495,
    370,
    255,
    '12. CUANDO USARLO',
    'Si el dataset no cabe en RAM o llegan datos continuamente. MSD: mas de 500k canciones y 90 rasgos de timbre.\n\nSe procesa un chunk, se actualizan pesos y se descarta. No barajar el archivo antes de respetar el split oficial train/test.',
    COLORS.amber,
    COLORS.amberFill,
  ),
  ...card(
    'gd',
    500,
    1495,
    370,
    255,
    '13. GD, SGD Y MINI-BATCH',
    'Batch GD: gradiente con todo N; estable, costoso.\nSGD: una muestra; rapido, muy ruidoso.\nMini-batch: B muestras; equilibrio practico.\n\nw <- w - eta * promedio(gradiente)\n\neta es la tasa de aprendizaje.',
    COLORS.amber,
    COLORS.amberFill,
  ),
  ...card(
    'partialFit',
    920,
    1495,
    390,
    255,
    '14. partial_fit EN 2 PASADAS',
    'Pasada 1: scaler.partial_fit(X_chunk) sobre TODO train.\nPasada 2: transform -> sgd.partial_fit por chunk.\n\npartial_fit conserva los pesos entre llamadas. Nunca ajustar el scaler con test. Pipeline no siempre ofrece partial_fit: manejar scaler y modelo por separado.',
    COLORS.amber,
    COLORS.amberFill,
  ),
  arrow(455, 1620, 38, 0, COLORS.amber),
  arrow(875, 1620, 38, 0, COLORS.amber),

  ...card(
    'learningRate',
    80,
    1805,
    390,
    270,
    '15. LEARNING RATE',
    'eta demasiado grande: salta sobre el minimo, el error oscila o diverge (NaN/inf).\neta demasiado pequena: entrenamiento estable pero lento.\n\nProbar ordenes de magnitud: 1e-4, 1e-3, 1e-2, 1e-1, 1. Detener temprano si RMSE deja de ser finito.',
    COLORS.coral,
    COLORS.coralFill,
  ),
  ...card(
    'schedules',
    520,
    1805,
    350,
    270,
    '16. SCHEDULES',
    'constant: eta = eta0\noptimal: eta_t = 1/[alpha(t+t0)]\ninvscaling: eta_t = eta0/t^power_t\n\nDecaer permite pasos grandes al inicio y ajuste fino despues. Ante concept drift, una tasa constante conserva capacidad de adaptacion.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'monitor',
    920,
    1805,
    390,
    270,
    '17. MONITOREO',
    'RMSE por chunk: senal ruidosa del proceso.\nRMSE de validacion por epoch: medida comparable.\n\nBarajar train entre epochs evita sesgo de orden. Validar en datos separados. Si la distribucion cambia, actualizar estadisticas con cuidado y vigilar concept drift.',
    COLORS.blue,
    COLORS.blueFill,
  ),

  text(80, 2140, 'EXTENSION · BUSQUEDA BAYESIANA DE HIPERPARAMETROS', 27, COLORS.violet),
  ...card(
    'bayesIdea',
    80,
    2195,
    390,
    290,
    '18. IDEA CENTRAL',
    'Busca buenos hiperparametros usando pocas evaluaciones costosas. En vez de probar una cuadricula completa, aprende una aproximacion de:\n\nf(theta) = error CV del modelo\n\nEl modelo sustituto (p. ej., proceso gaussiano o TPE) estima rendimiento e incertidumbre en puntos aun no evaluados.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'bayesLoop',
    520,
    2195,
    350,
    290,
    '19. CICLO BAYESIANO',
    '1) Evaluar algunos puntos iniciales.\n2) Ajustar el modelo sustituto.\n3) Maximizar una funcion de adquisicion.\n4) Evaluar el candidato con CV.\n5) Actualizar y repetir.\n\nLa adquisicion equilibra explotacion (zonas prometedoras) y exploracion (zonas inciertas). Ejemplos: EI, PI y UCB.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'bayesPractice',
    920,
    2195,
    390,
    290,
    '20. CUANDO Y COMO USARLA',
    'Conviene si cada entrenamiento/CV es caro, hay varios hiperparametros o el presupuesto es limitado. Para alpha usar rango log-uniforme, p. ej. 1e-4 a 1e4.\n\nNo garantiza el optimo global. Mantener Pipeline + CV para evitar leakage y reservar test para el final. Fijar random_state y registrar el historial.',
    COLORS.violet,
    COLORS.violetFill,
  ),
  ...card(
    'bayesCompare',
    80,
    2535,
    1230,
    175,
    'GRID VS. RANDOM VS. BAYES',
    'GridSearch: simple y reproducible, pero desperdicia pruebas en dimensiones poco importantes.  ·  RandomizedSearch: cubre mejor espacios grandes y es una linea base fuerte.  ·  Busqueda bayesiana: usa resultados previos para elegir la siguiente prueba; suele ser mas eficiente, pero agrega complejidad y su ventaja es menor cuando entrenar es barato o hay pocos candidatos.',
    COLORS.blue,
    COLORS.blueFill,
  ),

  text(80, 2775, 'CHECKLIST MENTAL', 27, COLORS.green),
  ...card(
    'checklist',
    80,
    2830,
    1230,
    185,
    'ANTES DE ENTRENAR',
    '1) Definir objetivo y metrica  ·  2) Separar train/test  ·  3) Revisar distribuciones, censura, outliers y skew  ·  4) Encapsular preprocessing  ·  5) Elegir Grid, Random o Bayes segun costo y espacio  ·  6) Ajustar solo con CV  ·  7) Evaluar test una vez  ·  8) Inspeccionar residuos y errores por segmento.',
    COLORS.green,
    COLORS.greenFill,
  ),
  text(
    80,
    3060,
    'Regla de oro: toda transformacion que aprende parametros se ajusta solo con entrenamiento.',
    23,
    COLORS.coral,
  ),
]

export const studyElements = convertToExcalidrawElements(skeleton, {
  regenerateIds: false,
})

export const studyInitialData = {
  elements: studyElements,
  appState: {
    viewBackgroundColor: COLORS.paper,
    currentItemFontFamily: 2,
  },
  scrollToContent: true,
}